# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='my.proto',
  package='motorcycle',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08my.proto\x12\nmotorcycle\"\xcf\x01\n\rYOLOv5Package\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x30\n\x06\x62\x62oxes\x18\x02 \x01(\x0b\x32 .motorcycle.YOLOv5Package.BBoxes\x12.\n\x05\x66rame\x18\x03 \x01(\x0b\x32\x1f.motorcycle.YOLOv5Package.Frame\x1a%\n\x05\x46rame\x12\r\n\x05shape\x18\x01 \x03(\x05\x12\r\n\x05\x66rame\x18\x02 \x01(\x0c\x1a\'\n\x06\x42\x42oxes\x12\r\n\x05shape\x18\x01 \x03(\x05\x12\x0e\n\x06\x62\x62oxes\x18\x02 \x01(\x0c\x62\x06proto3'
)




_YOLOV5PACKAGE_FRAME = _descriptor.Descriptor(
  name='Frame',
  full_name='motorcycle.YOLOv5Package.Frame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='shape', full_name='motorcycle.YOLOv5Package.Frame.shape', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame', full_name='motorcycle.YOLOv5Package.Frame.frame', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=191,
)

_YOLOV5PACKAGE_BBOXES = _descriptor.Descriptor(
  name='BBoxes',
  full_name='motorcycle.YOLOv5Package.BBoxes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='shape', full_name='motorcycle.YOLOv5Package.BBoxes.shape', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bboxes', full_name='motorcycle.YOLOv5Package.BBoxes.bboxes', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=232,
)

_YOLOV5PACKAGE = _descriptor.Descriptor(
  name='YOLOv5Package',
  full_name='motorcycle.YOLOv5Package',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='motorcycle.YOLOv5Package.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bboxes', full_name='motorcycle.YOLOv5Package.bboxes', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame', full_name='motorcycle.YOLOv5Package.frame', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_YOLOV5PACKAGE_FRAME, _YOLOV5PACKAGE_BBOXES, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=232,
)

_YOLOV5PACKAGE_FRAME.containing_type = _YOLOV5PACKAGE
_YOLOV5PACKAGE_BBOXES.containing_type = _YOLOV5PACKAGE
_YOLOV5PACKAGE.fields_by_name['bboxes'].message_type = _YOLOV5PACKAGE_BBOXES
_YOLOV5PACKAGE.fields_by_name['frame'].message_type = _YOLOV5PACKAGE_FRAME
DESCRIPTOR.message_types_by_name['YOLOv5Package'] = _YOLOV5PACKAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

YOLOv5Package = _reflection.GeneratedProtocolMessageType('YOLOv5Package', (_message.Message,), {

  'Frame' : _reflection.GeneratedProtocolMessageType('Frame', (_message.Message,), {
    'DESCRIPTOR' : _YOLOV5PACKAGE_FRAME,
    '__module__' : 'my_pb2'
    # @@protoc_insertion_point(class_scope:motorcycle.YOLOv5Package.Frame)
    })
  ,

  'BBoxes' : _reflection.GeneratedProtocolMessageType('BBoxes', (_message.Message,), {
    'DESCRIPTOR' : _YOLOV5PACKAGE_BBOXES,
    '__module__' : 'my_pb2'
    # @@protoc_insertion_point(class_scope:motorcycle.YOLOv5Package.BBoxes)
    })
  ,
  'DESCRIPTOR' : _YOLOV5PACKAGE,
  '__module__' : 'my_pb2'
  # @@protoc_insertion_point(class_scope:motorcycle.YOLOv5Package)
  })
_sym_db.RegisterMessage(YOLOv5Package)
_sym_db.RegisterMessage(YOLOv5Package.Frame)
_sym_db.RegisterMessage(YOLOv5Package.BBoxes)


# @@protoc_insertion_point(module_scope)
